/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import datos.Configuracion;
import datos.DataSet;
import datos.Perfiles;
import datos.Usuarios;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class Main extends javax.swing.JFrame {

    private Usuarios usuario;
    private Configuracion configuracion;
    private int puerto;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    public void iniciar() {

        setResizable(false);
        setLocationRelativeTo(null);

        cargarImanes();
        
        nombre.setText(usuario.getNombres() + " " + usuario.getApellidos());
        perfil.setText(usuario.getPerfil().getNombreperfil());
        configuracion = new Configuracion();
        switch (usuario.getIdperfil()) {
            case 1:
                puerto = Integer.parseInt(configuracion.accderPorpiedades("puerto1"));

                break;

            case 2:
                fileM.setVisible(false);
                menuRegistro.setVisible(false);
                aggUM.setVisible(false);
                updUM.setVisible(false);
                puerto = Integer.parseInt(configuracion.accderPorpiedades("puerto2"));
                break;
        }
        lbPuerto.setText(puerto + "");
        ///lbPuerto.setText("");
       
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
    }

    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
    }
    
    
    private void cargarImanes(){
        fileM.setIcon(obtenerIcono(40, 40, "file.png"));
        ArtM.setIcon(obtenerIcono(40, 40, "art.png"));
        registroM.setIcon(obtenerIcono(40, 40, "user.png"));     
        confM.setIcon(obtenerIcono(30, 30, "setup.png"));
        PortM.setIcon(obtenerIcono(30, 30, "port.png"));
        UserM.setIcon(obtenerIcono(30, 30, "userP.png"));
        AdminM.setIcon(obtenerIcono(30, 30, "admin.png"));
        
        menuRegistro.setIcon(obtenerIcono(30, 30, "resgister.png"));
        ListaM.setIcon(obtenerIcono(30, 30, "listaU.png"));
        aggUM.setIcon(obtenerIcono(30, 30, "addP.png"));
        updUM.setIcon(obtenerIcono(30, 30, "box_edit.png"));
        listUM.setIcon(obtenerIcono(30, 30, "listUP.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbPuerto = new javax.swing.JLabel();
        lbMensaje = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileM = new javax.swing.JMenu();
        confM = new javax.swing.JMenuItem();
        PortM = new javax.swing.JMenu();
        AdminM = new javax.swing.JMenuItem();
        UserM = new javax.swing.JMenuItem();
        registroM = new javax.swing.JMenu();
        menuRegistro = new javax.swing.JMenuItem();
        ListaM = new javax.swing.JMenuItem();
        ArtM = new javax.swing.JMenu();
        aggUM = new javax.swing.JMenuItem();
        updUM = new javax.swing.JMenuItem();
        listUM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bienvenido"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Hola, ");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setText("Perfil:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton2.setText("Enviar Dato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Puerto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPuerto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        fileM.setText("Archivo");

        confM.setText("Configurar");
        confM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confMActionPerformed(evt);
            }
        });
        fileM.add(confM);

        PortM.setText("Cambiar puertos");

        AdminM.setText("Administrador");
        AdminM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminMActionPerformed(evt);
            }
        });
        PortM.add(AdminM);

        UserM.setText("Usuario");
        UserM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMActionPerformed(evt);
            }
        });
        PortM.add(UserM);

        fileM.add(PortM);

        jMenuBar1.add(fileM);

        registroM.setText("Usuarios");

        menuRegistro.setText("Registro");
        menuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroActionPerformed(evt);
            }
        });
        registroM.add(menuRegistro);

        ListaM.setText("Lista de Usuarios");
        ListaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMActionPerformed(evt);
            }
        });
        registroM.add(ListaM);

        jMenuBar1.add(registroM);

        ArtM.setText("Articulos");

        aggUM.setText("Agregar");
        aggUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggUMActionPerformed(evt);
            }
        });
        ArtM.add(aggUM);

        updUM.setText("Actualizar");
        updUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updUMActionPerformed(evt);
            }
        });
        ArtM.add(updUM);

        listUM.setText("Listar");
        listUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUMActionPerformed(evt);
            }
        });
        ArtM.add(listUM);

        jMenuBar1.add(ArtM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confMActionPerformed
        Configure conf = new Configure(this, true);
        conf.setLocationRelativeTo(this);
        conf.setVisible(true);
    }//GEN-LAST:event_confMActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroActionPerformed
        try {
            Socket s = new Socket(configuracion.accderPorpiedades("IP"), puerto);
            DataOutputStream out;
            out = new DataOutputStream(s.getOutputStream());
            out.writeUTF("l");
            ObjectInputStream in = new ObjectInputStream(s.getInputStream());
            List<Perfiles> list = (List<Perfiles>) in.readObject();
            if (list != null) {
                Registro r = new Registro(this, true);
                r.listaPerfiles = list;
                r.inicializar();
            } else {
                System.out.println("error");
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuRegistroActionPerformed

    private void ListaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMActionPerformed
        try {
            Socket s = new Socket(configuracion.accderPorpiedades("IP"), puerto);
            DataOutputStream out;
            out = new DataOutputStream(s.getOutputStream());
            out.writeUTF("u");
            ObjectInputStream in = new ObjectInputStream(s.getInputStream());
            DataSet dt = (DataSet) in.readObject();
            VerUsuarios v = new VerUsuarios(this, true);
            v.setDt(dt);
            v.iniciarlizar();
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ListaMActionPerformed

    private void AdminMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminMActionPerformed
        Cambio c = new Cambio(this, true);
        c.setIsAdmin(true);
        c.inicializar();
    }//GEN-LAST:event_AdminMActionPerformed

    private void UserMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMActionPerformed
        Cambio c = new Cambio(this, true);
        c.setIsAdmin(false);
        c.inicializar();
    }//GEN-LAST:event_UserMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Socket s = new Socket(configuracion.accderPorpiedades("IP"), puerto);
            DataOutputStream out;
            out = new DataOutputStream(s.getOutputStream());
            out.writeUTF("d");
            ObjectOutputStream ou = new ObjectOutputStream(s.getOutputStream());
            ou.writeUnshared(usuario);
            DataInputStream in = new DataInputStream(s.getInputStream());
            lbMensaje.setText(in.readUTF());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aggUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggUMActionPerformed
        Vista_articulo vista_articulo=new Vista_articulo();
        controladorArticulo art= new controladorArticulo(vista_articulo);
        vista_articulo.setLocation(jDesktopPane1.getWidth()/2 - vista_articulo.getWidth()/2, 10);
        jDesktopPane1.add(vista_articulo);
        art.IniciarVistaArticulo();
    }//GEN-LAST:event_aggUMActionPerformed

    private void updUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updUMActionPerformed
          Vista_articulo vista_articulo=new Vista_articulo();
        controladorArticulo art= new controladorArticulo(vista_articulo);
        vista_articulo.setLocation(jDesktopPane1.getWidth()/2 - vista_articulo.getWidth()/2, 10);
        jDesktopPane1.add(vista_articulo);
        art.op=2;
        art.IniciarVistaArticulo();
    }//GEN-LAST:event_updUMActionPerformed

    private void listUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUMActionPerformed
        Articulo vista_articulo= new Articulo();
        controladorListaArticulo coArticulo= new controladorListaArticulo(vista_articulo);
        vista_articulo.setLocation(jDesktopPane1.getWidth()/2 - vista_articulo.getWidth()/2, 10);
        jDesktopPane1.add(vista_articulo);        
        coArticulo.IniciarVistaProducto();
    }//GEN-LAST:event_listUMActionPerformed

    public Icon obtenerIcono(int ancho, int alto, String file) {
        ImageIcon image = new ImageIcon("recursos/" + file);
        Icon icono = new ImageIcon(image.getImage().getScaledInstance(ancho, alto, Image.SCALE_REPLICATE));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdminM;
    private javax.swing.JMenu ArtM;
    private javax.swing.JMenuItem ListaM;
    private javax.swing.JMenu PortM;
    private javax.swing.JMenuItem UserM;
    private javax.swing.JMenuItem aggUM;
    private javax.swing.JMenuItem confM;
    private javax.swing.JMenu fileM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbPuerto;
    private javax.swing.JMenuItem listUM;
    private javax.swing.JMenuItem menuRegistro;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JMenu registroM;
    private javax.swing.JMenuItem updUM;
    // End of variables declaration//GEN-END:variables
}
